### ISSUE TITLE
2.14.0 Update Causing "TypeError: module__default.default.createRequire is not a function" Error.

### ISSUE THREAD

**Issue by JohnKearney2020** [hbenl/vscode-mocha-test-adapter#218]
Mocha Test Explorer: v2.14.0
Node: 10.24.1
VsCode: 1.69.1

After updating to 2.14.0 I am getting this error and I am unable to run any tests. I've attached the error message displayed in the 'OUTPUT' tab of my terminal.

![image](https://user-images.githubusercontent.com/59856639/178763906-95aebb0c-33e7-4105-8cd3-ad85ed534e04.png)

![image](https://user-images.githubusercontent.com/59856639/178764081-0989ced6-e144-4aa3-8e53-3d15b148e0c3.png)

I was able to roll back to version 2.13.5 as a workaround.

**Comment by hbenl** [comment]
I started using a node method that wasn't implemented yet in Node 10. I've added a fallback for old Node versions in version 2.14.1 of this extension.
