### ISSUE TITLE
The extension does not work with mocha version 12.0.x

### ISSUE THREAD

**Issue by FairPlayer4** [hbenl/vscode-mocha-test-adapter#273]
See title, if I install mocha version 11.8.0 it works fine.

In my VS Code Extension settings I added "mochaExplorer.require":  ["tsx"] so my tests would load.
I have no .mocharc.json in my project.
Maybe a configuration problem in my project but I couldn't find the issue. AI thought it might be a breaking change in mocha version 12.0.0 since it worked with version 11.8.0

In the log I see the following error:

node:internal/modules/cjs/loader:1564
  const err = new Error(message);
              ^

Error: Cannot find module 'C:\SourceCode\GCP\my-project\node_modules\mocha/lib/utils'
Require stack:
- c:\Users\My.User\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.14.4\out\worker\bundle.js
    at node:internal/modules/cjs/loader:1564:15
    at j._resolveFilename (file:///C:/SourceCode/GCP/my-project/node_modules/tsx/dist/register-SoqaU4rg.mjs:2:17957)
    at nextResolveSimple (C:\SourceCode\GCP\my-project\node_modules\tsx\dist\register-OY9cqBEN.cjs:10:1006)
    at C:\SourceCode\GCP\my-project\node_modules\tsx\dist\register-OY9cqBEN.cjs:9:4959
    at C:\SourceCode\GCP\my-project\node_modules\tsx\dist\register-OY9cqBEN.cjs:9:4261
    at resolveTsPaths (C:\SourceCode\GCP\my-project\node_modules\tsx\dist\register-OY9cqBEN.cjs:10:759)
    at Module._resolveFilename (C:\SourceCode\GCP\my-project\node_modules\tsx\dist\register-OY9cqBEN.cjs:10:1199)
    at wrapResolveFilename (node:internal/modules/cjs/loader:1118:27)
    at defaultResolveImplForCJSLoading (node:internal/modules/cjs/loader:1142:10)
    at defaultResolve (node:internal/modules/cjs/loader:1199:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\My.User\\.vscode\\extensions\\hbenl.vscode-mocha-test-adapter-2.14.4\\out\\worker\\bundle.js'
  ]
}

Node.js v24.21.0
